packages:
  - apps/*
  - packages/*
nodeLinker: hoisted
storeDir: .pnpm-store
allowBuilds:
  esbuild: true
  node-pty: true
  electron-winstaller: true
  electron: true
onlyBuiltDependencies:
  - esbuild
  - node-pty
  - electron-winstaller
blockExoticSubdeps: false
