import { z } from "zod";

export const ApprovalKindSchema = z.enum(["command", "fileChange", "permission"]);
export type ApprovalKind = z.infer<typeof ApprovalKindSchema>;

export const ApprovalRequestSchema = z.object({
  approvalId: z.string(), // apr_ prefix, generated by Aether
  threadId: z.string(),
  runId: z.string().optional(),
  runtimeId: z.string(),
  backendId: z.string(),
  kind: ApprovalKindSchema,
  title: z.string(),
  detail: z.string().optional(),
  risk: z.enum(["low", "medium", "high"]).default("medium"),
  createdAt: z.string(),
});
export type ApprovalRequest = z.infer<typeof ApprovalRequestSchema>;

export const ApprovalDecisionValueSchema = z.enum([
  "approved_once",
  "approved_session",
  "rejected",
  "cancelled",
]);
export type ApprovalDecisionValue = z.infer<typeof ApprovalDecisionValueSchema>;

export interface ApprovalResponse {
  approvalId: string;
  decision: ApprovalDecisionValue;
}
